# Generated by Django 5.1 on 2024-12-26 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Get",
            new_name="Post",
        ),
    ]
